{% set name = "cuda-cccl" %}
{% set version = "12.4.127" %}
{% set cccl_version = "2.3.2" %}
{% set cuda_version = "12.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

# CUDA C++ Core Libraries (CCCL) includes thrust, cub, and libcudacxx. These are header-only libraries.
# The cccl package ships CCCL headers in the environment's include directory for use in downstream recipes that require CCCL. It follows CCCL upstream versioning. Use this package to say, "I want a specific version of CCCL headers when building my package (which may be newer than the versions shipped in the latest CUDA Toolkit)."
# The cuda-cccl_{{ target_platform }} package (e.g. cuda-cccl_linux-64) ships CCCL headers in 'targets/.../include' that can be used by nvcc, the CUDA compiler. It follows CUDA Toolkit versioning. This package should only be a dependency of the cuda-cudart / cuda-nvcc packages that require CCCL to function. It is target-specific to allow for cross-compilation, as a dependency of cuda-nvcc.
# The cuda-cccl package is a metapackage that depends on cccl and cuda-cccl_{{ target_platform }} to ensure that versions are consistent. Use this package to say, "I want to build with the thrust headers that shipped with CUDA Toolkit X.Y" by adding dependencies on `cuda-cccl` and `cuda-version X.Y`.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cccl/{{ platform }}/cuda_cccl-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: e1636f27a142d24e73dfd831c54bbf5575b498fd5900648d7372fae46f824fdf  # [linux64]
  sha256: 3304e563ed089be1129f79d8e45c9badc8eeba155c8b672f9659f223494edcd9  # [ppc64le]
  sha256: 171073fd6557360b9db7f8559e17b1bb55679aadd5158681318ed9be67e54667  # [aarch64]
  sha256: 908742d8f3c6fdd6d1d6316a7b919b5c506474f9551f491aa7335cb4f50bffbd  # [win]

build:
  number: 2
  skip: true  # [osx]

test:
  commands:
    - test -d $PREFIX/lib/cmake                      # [linux]
    - test -d $PREFIX/targets/{{ target_name }}/lib  # [linux]
    - if not exist %LIBRARY_LIB%\{{ target_name }}\cmake exit 1    # [win]
    - if not exist %LIBRARY_INC%\targets\{{ target_name }} exit 1  # [win]
    # Extracts the correct cccl version from Nvidia's cuda_cccl archive, and compares it against the version of the cccl conda package
    - CCCL_VERSION_MAJOR=$(grep "set(CCCL_VERSION_MAJOR" $PREFIX/targets/{{ target_name }}/lib/cmake/cccl/cccl-config-version.cmake | cut -d " " -f2 | tr -d ')')   # [linux]
    - CCCL_VERSION_MINOR=$(grep "set(CCCL_VERSION_MINOR" $PREFIX/targets/{{ target_name }}/lib/cmake/cccl/cccl-config-version.cmake | cut -d " " -f2 | tr -d ')')   # [linux]
    - CCCL_VERSION_PATCH=$(grep "set(CCCL_VERSION_PATCH" $PREFIX/targets/{{ target_name }}/lib/cmake/cccl/cccl-config-version.cmake | cut -d " " -f2 | tr -d ')')   # [linux]
    - if [[ "${CCCL_VERSION_MAJOR}.${CCCL_VERSION_MINOR}.${CCCL_VERSION_PATCH}" != {{ cccl_version }} ]]; then exit 1; fi                                           # [linux]

outputs:
  - name: cuda-cccl
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - cuda-cccl_{{ target_platform }} =={{ version }}
        - cccl =={{ cccl_version }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    # Tests are defined at the top level, due to package/output name conflicts.
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: 'CUDA C++ Core Libraries'
      description: |
        CUDA C++ Core Libraries
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-cccl_{{ target_platform }}
    build:
      noarch: generic
    files:
      - targets  # [linux]
      - Library\lib\x64\cmake                      # [win]
      - Library\include\targets\{{ target_name }}  # [win]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -d $PREFIX/targets/{{ target_name }}/lib      # [linux]
        - test -d $PREFIX/targets/{{ target_name }}/include  # [linux]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cmake exit 1    # [win]
        - if not exist %LIBRARY_INC%\targets\{{ target_name }} exit 1  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: 'CUDA C++ Core Libraries'
      description: |
        CUDA C++ Core Libraries
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: 'CUDA C++ Core Libraries'
  description: |
    CUDA C++ Core Libraries
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
